export const defaultMetaFullTextResearcherGuidanceLines = [
  "These rules are scoped to the current Musician PRMD pain prevalence project. Do not apply them globally to unrelated meta-analysis topics.",
  "The current project status is AI full-text triage plus extraction drafting, not completed screening. Human reviewer 1, reviewer 2, and PI adjudication remain required before final study selection.",
  "Preserve AI-only model drafts separately from human-reviewed decisions. Human corrections must not overwrite the original AI-only snapshot used for model-performance comparison.",
  "Record model/profile traceability when available: model name, provider/base URL, protocol version, prompt version/hash, extraction schema version/hash, and source-file checksum.",
  "Do not invent values. Use null or an empty string when a value is not explicitly supported.",
  "Eligibility is only a draft for human verification; never present an AI decision as final inclusion.",
  "Prefer quantitative inclusion only when original observational data, instrument/instrument-group data, region-specific pain outcomes, and extractable denominator/numerator or prevalence are present.",
  "Exclude RCTs, treatment/intervention/effect studies, case reports, reviews, conference-only records, non-English full text, wrong population, wrong outcome, and studies without extractable denominator-based pain outcomes.",
  "Extract numbers exactly as reported. If only percent is reported without denominator, put a note instead of fabricating n.",
  "Actively extract study-level characteristics that are usually in title page, abstract, Methods, Table 1, participant/general characteristics tables, affiliations, Results tables, figures, and supplements.",
  "Always look for and fill first_author, year, country, design, sample_size_total, sample_size_analyzed, population_source, professional_status, mean_age, female_percent, playing_hours, years_experience, instrument_group_reported, and specific_instrument when the article reports them.",
  "Derive country from study setting, recruitment site, sample description, or author affiliation only when no explicit study country is reported; note the source in fieldEvidence.",
  "Search tables/figures for instrument-specific denominators, body-region pain counts/percentages, recall window, and PRMD/pain definitions before marking these cells missing.",
  "For every non-empty extracted numeric cell, provide cell-level evidence with field name, value, short exact excerpt, and page/table/figure/supplement hint when available.",
  "For every non-empty key descriptive cell, especially first_author, country, sample_size_total, mean_age, female_percent, instrument_group_reported, and specific_instrument, provide fieldEvidence when the text/table/affiliation supports it.",
  "Do not fill instrument group or asymmetry mapping from background-only mentions; use actual sample/group information only.",
  "Never infer left/right laterality from instrument playing side. Fill left/right cells only when the article explicitly reports left/right outcomes.",
  "If an article is treatment/intervention/RCT/effect-focused, do not mark it quantitative unless independent baseline observational prevalence with explicit denominator/numerator is clearly extractable.",
  "If a numeric cell lacks source evidence, leave the cell empty or mark it needs review instead of fabricating a value.",
  "Instrument-specific observational studies are eligible for quantitative inclusion even when they are not core orchestral comparative studies, if instrument-specific site/laterality pain counts with denominators are extractable.",
  "When a table reports site-specific or laterality-specific pain counts and percentages with a common denominator, extract the n/total pairs from the table. Do not downgrade eligibility merely because the article reports only the highest-prevalence sites; code unreported sites as NR, not 0.",
  "If an overall prevalence numerator and percentage disagree internally, flag a numerator-percentage discrepancy in notes_on_extractability and validationIssues, but do not discard internally consistent site-specific table rows.",
  "For classical guitar studies, keep asymmetry_group as unclassified/other unless a protocol-approved guitar asymmetry class exists. Do not assign a high/moderate/low asymmetry group by intuition.",
  "Distinguish playing-related musculoskeletal pain over a recall period from strict PRMD definitions requiring performance limitation; record the actual outcome definition.",
  "Calibration example: If the article is Zuhdi et al. 2020 Occupational Health Problems of Classical Guitarists, Table 5 reports site- and laterality-specific 12-month pain counts with denominator n=190. Treat it as include_quantitative for instrument-specific observational extraction, flag the overall 168/190 vs 88.9% inconsistency, keep unreported sites as NR, and keep guitar asymmetry_group as unclassified/other. Do not transfer these exact values to other papers.",
  "If the only quantitative pain outcome is a composite anatomical outcome such as neck-shoulder complaint, neck/shoulder/interscapular pain combined, or any-region upper-body pain, and the article does not report separate region-specific and laterality-specific estimates, do not classify it as primary include_quantitative for the region/laterality meta-analysis.",
  "For composite-outcome papers that are otherwise protocol-relevant, use include_narrative_support or record primary-analysis exclusion with secondary/narrative inclusion. Extract reconstructable group n/total values as secondary evidence only, not as primary region/laterality rows.",
  "When exposure groups combine instrument, arm elevation, posture, and playing time, preserve the exact reported group labels. Do not reinterpret them as a pure asymmetry effect and do not split pooled violin/viola or other pooled instruments unless the article reports separate values.",
  "Calibration example: If the article is Nyman et al. 2007 Work Postures and Neck-Shoulder Pain Among Orchestra Musicians, Table II percentages can reconstruct neck-shoulder complaint cases by posture/playing-time group, but the outcome is current composite neck, shoulder, or interscapular pain with no separate anatomical or left/right estimates. Treat primary region/laterality meta-analysis as excluded and retain for narrative or secondary composite-outcome synthesis. Do not transfer these exact values to other papers.",
  "If participants were preselected because they already had pain or disability, do not treat all included participants as prevalence cases. A symptomatic cohort or case-only sample lacks a valid at-risk denominator for primary prevalence meta-analysis.",
  "Continuous outcome means such as VAS, NDI, SF-36, quality-of-life, severity, or disability scores are not pain_n/total_n prevalence data. Keep them for narrative synthesis or a separately prespecified continuous-outcome analysis only.",
  "Classify the actual recruited population, not the title wording. If the sample is music college students, record student/trainee status even when the title says professional musicians.",
  "Flag attrition and unclear stage-specific instrument sample sizes when the analysis set is smaller than eligible or enrolled participants, especially if dropout may be related to musculoskeletal overload or pain.",
  "Calibration example: If the article is Piatkowska et al. 2016 Cervical Pain in Young Professional Musicians - Quality of Life, it is a repeated-measures symptomatic cohort of music students preselected for cervical pain. Exclude from primary prevalence meta-analysis; retain only for narrative or separately prespecified continuous VAS/NDI/SF-36 analysis. Do not code 45/45 as cervical pain prevalence. Do not transfer these exact values to other papers.",
  "If prevalence values are reported only for broad body-region groups joined by 'or' such as head or neck, back/chest/shoulders, arms or wrists, or legs or hips, do not split them into standard anatomical site rows.",
  "If a PRMD/injury prevalence outcome lacks a fixed recall window or mixes current, past, diagnosed injury, self-reported symptoms, and location-only responses, do not combine it with point, 7-day, 12-month, or lifetime pain prevalence unless the article explicitly defines the time window and case definition.",
  "Graph-reconstructed numerators can be kept as supplementary quantitative evidence when internally checked, but graph-only broad-region values without laterality and fixed timeframe are not primary site/laterality prevalence rows.",
  "Flag differential missingness when one subgroup has more missing body-location responses than another; do not interpret such body-region differences as clean subgroup effects.",
  "Check for overlapping cohorts or secondary analyses from the same questionnaire/sample. Link related reports and do not pool them as independent studies.",
  "Calibration example: If the article is Brusky 2010 The High Prevalence of Injury Among Female Bassoonists, treat it as narrative/support with limited supplementary sex-stratified broad-region PRMD extraction. Exclude from primary site/laterality prevalence meta-analysis because the body regions are broad composites, laterality is not reported as n/N, recall period is unclear, location missingness differs by sex, and the overall 88% prevalence is not fully reconcilable with sex-specific estimates. Check overlap with Brusky 2009. Do not transfer these exact values to other papers.",
  "If a study reports only overall pain while playing, pain after playing, performance interruption scores, or number of marked pain sites, but no anatomical site-specific and laterality-specific n/N, classify it as narrative/support or supplementary overall-pain evidence rather than primary site/laterality prevalence.",
  "Do not merge distinct overall pain outcomes. For example, pain while playing and at least one pain site marked are different outcomes and must not be treated as interchangeable PRMD prevalence values.",
  "A 0-10 VAS, never-always scale, or percent of performance affected is a continuous/frequency/severity measure unless the article defines a binary case threshold. Do not create pain_n from VAS means or frequency scores.",
  "Risk-factor correlation or regression findings in small cross-sectional convenience samples should be retained as exploratory narrative risk-factor evidence, not causal conclusions.",
  "Calibration example: If the article is Yoshimura et al. 2006 Risk Factors for Piano-related Pain among College Students, exclude from primary anatomical-region/laterality prevalence meta-analysis. It can retain narrative risk-factor synthesis and limited supplementary overall piano-related pain: 86% of 35 as reconstructed 30/35 pain while playing, and 32/35 as at least one pain site marked. Keep those as separate outcomes, record recall period as not reported, strict interference-based PRMD as no, and do not infer site/laterality counts. Do not transfer these exact values to other papers.",
  "If the official analyzed sample size conflicts with pain figures, cluster/confusion matrices, or logistic-regression denominators, do not choose a convenient n/N. Mark overall pain numerator/denominator as NR or internally inconsistent until the source can be reconciled.",
  "If pain/no-pain category direction is contradictory across figures, text, or model tables, do not use the article for overall pain-prevalence pooling, even when a figure appears to show a binary split.",
  "Do not pool risk-factor odds ratios from small cross-sectional models when confidence intervals, standard errors, exact p values, or stable model definitions are absent. Keep those ORs as narrative-only risk-factor evidence.",
  "Calibration example: If the article is Santos et al. 2024 Odds ratio of occurrence of pain, postural changes, and disabilities of violinists, exclude from primary anatomical-region/laterality prevalence meta-analysis and from overall pain-prevalence pooling. The official sample size is 38 but pain figures/model outputs use 39 observations, pain/no-pain allocation is contradictory, recall period and playing-related case definition are unclear, site/laterality n/N is absent, VAS/DASH are not extractable for pooling, and reported posture/practice ORs lack confidence intervals. Retain only limited narrative risk-factor evidence. Do not transfer these exact values to other papers.",
  "For risk-of-bias fields, extract only article-supported facts needed for observational-study RoB judgment: sampling/recruitment, measurement/outcome definition, confounding/adjustment, missing data, selective reporting, response rate, funding, and conflict-of-interest statements.",
  "For publication-bias fields, collect only study-level inputs that later funnel/small-study-effect checks need: outcome group, effect size/prevalence input, standard error or data needed to compute it, and whether the row is eligible for funnel/small-study assessment. Do not claim publication bias from a single article.",
  "Use rob_supporting_quote and rob_page_table for short evidence excerpts or page/table/supplement hints. If the full text lacks evidence, leave the field empty and list it in manual_required_fields.",
  "For this prevalence/cross-sectional review, prefer a prevalence-appropriate RoB frame such as JBI prevalence checklist, Hoy risk-of-bias tool, AXIS, or JBI analytical cross-sectional checklist. RoB 2 and ROBINS-I are not the primary RoB tools for the primary prevalence dataset; reserve them only for intervention/nonrandomized-intervention questions if separately analyzed.",
  "Keep evidence excerpts short.",
  "Use eligibility.confidence as a 0-100 percentage, not a 0-1 probability. Return 96 for 96% confidence; do not return 0.96.",
  "Use reviewEvaluation.score and criterion scores as 0-100 quality scores, not 1-5 scores. Convert 4/5 to 80 before returning JSON.",
  "Grade mapping is high=85-100 with no major unresolved issue, moderate=65-84 or usable with limited missing fields, low=40-64 or major manual checks needed, unsafe=0-39/fallback/failed/not usable.",
  "Select quantitative inclusion only when decision is include_quantitative, confidence is at least 80, score is at least 65, grade is high or moderate, denominator/numerator or prevalence is extractable, numeric fieldEvidence is present, and the outcome maps to the protocol's primary region/laterality rows.",
  "Use include_narrative_support when the article is relevant but quantitative n/total or effect-size extraction is incomplete, when numeric data exist but the outcome/grouping/timeframe is incompatible with the primary region/laterality meta-analysis, when only continuous symptom/disability scores are available, when only supplementary graph-reconstructed broad-region data are available, or when only overall pain/risk-factor evidence is available.",
  "Accept exclusion only when confidence is at least 80 and a fixed exclusion reason is clearly supported by the full text.",
  "Use uncertain/human verification when confidence is below 70, score is below 65, grade is low/unsafe, model drafts disagree, critical fields are missing, or numeric source evidence is absent.",
  "Also evaluate the quality of your own screening/extraction using the reviewEvaluation criteria below.",
  "Return only one JSON object.",
];

export const defaultMetaFullTextResearcherGuidance = defaultMetaFullTextResearcherGuidanceLines
  .map((line) => `- ${line}`)
  .join("\n");

export function normalizeMetaFullTextResearcherGuidance(value: string | null | undefined) {
  const normalized = (value ?? "")
    .replace(/\r\n/g, "\n")
    .split("\n")
    .map((line) => line.trimEnd())
    .join("\n")
    .trim();
  return (normalized || defaultMetaFullTextResearcherGuidance).slice(0, 12_000);
}
